### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by molihub** [vuejs/vue-devtools#1017]
### Version
5.1.0

### Browser and OS info
npm@6.4.1 3   registry = "https://registry.npmjs.org/"  node@v10.15.1

### Steps to reproduce
```
npm install -g @vue/devtools
C:\Users\Administrator\AppData\Roaming\npm\vue-devtools -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\devtools\bin.js

> electron@1.7.16 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\devtools\node_modules\electron
> node install.js

C:\Users\Administrator\AppData\Roaming\npm\node_modules\@vue\devtools\node_modules\electron\install.js:48
  throw err
  ^

Error: connect ETIMEDOUT 52.216.238.115:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.16 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.16 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-21T06_21_47_976Z-debug.log
```

### What is expected?
success install.

### What is actually happening?
Error: connect ETIMEDOUT 52.216.238.115:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)

---
Why does installer access 52.216.238.115:443(It seam that is aws.amazon.com)
In my *.log file:
```
7 http fetch GET 304 https://registry.npmjs.org/@vue%2fdevtools 3876ms (from cache)
8 silly pacote tag manifest for @vue/devtools@latest fetched in 3933ms
....
....
....
6848 verbose stack Error: electron@1.7.16 postinstall: `node install.js`
6848 verbose stack Exit status 1
6848 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
6848 verbose stack     at EventEmitter.emit (events.js:189:13)
6848 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
6848 verbose stack     at ChildProcess.emit (events.js:189:13)
6848 verbose stack     at maybeClose (internal/child_process.js:970:16)
6848 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
6849 verbose pkgid electron@1.7.16
```

**Comment by index23** [comment]
@molihub  `yarn global add @vue/devtools` works for me. Try using `yarn` instead of `npm`.

**Comment by molihub** [comment]
> 
> 
> @molihub `yarn global add @vue/devtools` works for me. Try using `yarn` instead of `npm`.

Thanks for your replay! 
Success of `yarn` does not mean that npm installer works fine, so I think that this issue is still active.
