### ISSUE TITLE
Electron version not loading @vue/devtools@5.1.1

### ISSUE THREAD

**Issue by dillingham** [vuejs/vue-devtools#1070]
```
Uncaught Exception:
/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/index.js:3:19)

```

**Comment by keithgulbro** [comment]
@dillingham I have the same problem, have you found a solution?

**Comment by dillingham** [comment]
@keithgulbro someone has a workaround here https://github.com/vuejs/vue-devtools/issues/1071#issuecomment-534833944

**Comment by ysk8** [comment]
I have the same issue. For now the workaround suggested by @dillingham is working for me!

**Comment by fsworld009** [comment]
Same issue with 5.3.3

The error is because of the `ws` package, manually install an older version and reinstall vue devtools works for me.

(I'm using vue devtools as a local dev dependency)
```bash
npm install ws@6.1.4 -D
npm uninstall @vue/devtools
npm install -D @vue/devtools
```
