### ISSUE TITLE
Javascript error when starting Electron app on OSX

### ISSUE THREAD

**Issue by JamieMcDonnell** [vuejs/vue-devtools#1073]
### Version
5.1.1

### Browser and OS info
OXS Mojave 10.14.4

### Steps to reproduce
I followed the install steps here:
https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md

After running "vue-devtools" I see a javascript error popup containing the following:
```
Uncaught Exception:
/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/devtools/node_modules/ws/index.js:3:19)
```

### What is expected?
The vue-devtools electron app should run

### What is actually happening?
I see a javascript error popup instead. No vue-devtools is shown

---
I want to debug my iOS app on my iPad (over local network) with devtools running on my mac

**Comment by martinsotirov** [comment]
I get the same thing.

**Comment by keithgulbro** [comment]
Same error, any update?

**Comment by Amorites** [comment]
workaround here https://github.com/vuejs/vue-devtools/issues/1071#issuecomment-535153123

**Comment by LennonSantos** [comment]
mesmo erro

**Comment by edubasabe** [comment]
I get the same JS error.
<img width="463" alt="Captura de Pantalla 2019-10-04 a la(s) 10 34 32" src="https://user-images.githubusercontent.com/9272567/66211506-a4711980-e692-11e9-8ef1-fe8c144efcf9.png">

**Comment by zp00v0518** [comment]
I get the same JS error.

**Comment by 50l3r** [comment]
Same error

**Comment by antonioortegajr** [comment]
Did work for me on 

OSX Catalina v10.15.1
Node v11.12.0
