### ISSUE TITLE
Dev tools freeze after click on "new"

### ISSUE THREAD

**Issue by nicooprat** [vuejs/vue-devtools#1075]
### Version
5.1.1

### Browser and OS info
Brave Version 0.68.138 Chromium: 77.0.3865.75

### Steps to reproduce
Open Vue Devtools, click on "Settings (new)" tab.

### What is expected?
Settings pane opens.

### What is actually happening?
Vue Devtools freezes. I need to close Chrome devtools.

---
Reopening https://github.com/vuejs/vue-devtools/issues/1061 as it's unresolved but didn't use the template. 

![64432109-c12a2980-d0b3-11e9-9e53-41abe7359548](https://user-images.githubusercontent.com/645641/65878667-dfbbd180-e38e-11e9-8baa-623818b4969f.gif)

**Comment by felubra** [comment]
The problem seems to be only in Chrome, in firefox, I could not reproduce this issue.

**Comment by bennyty** [comment]
Error I pulled from the vue-devtools frame console.
```
TypeError: Cannot read property '$options' of undefined
    at ww.c.r.a.config.errorHandler (devtools.js:51)
    at ie (devtools.js:13)
    at ne (devtools.js:13)
    at Array.<anonymous> (devtools.js:13)
    at le (devtools.js:13)
re @ devtools.js:13

devtools.js:13
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at a.provide (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:51:408247)
    at Se (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:15082)
    at a.t._init (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:34428)
    at new a (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:35694)
    at an (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:21615)
    at init (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:20481)
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:21817)
    at p (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:44114)
    at h (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:43743)
    at H (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:13:46346)
```

**Comment by hay** [comment]
This is a known bug when blocking third-party cookies. See the workaround that works for me [over here](https://github.com/vuejs/vue-devtools/issues/979#issuecomment-529497634).

**Comment by nicooprat** [comment]
Thanks @hay, it worked indeed. In Brave I found the settings in `chrome://settings/content/cookies?search=cookie`. Click `add` in `whitelist`: `chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/` which will be translated to:

![image](https://user-images.githubusercontent.com/645641/66116837-b5a72100-e5d3-11e9-8a9c-9dbba656a13d.png)

I think we should let the issue open for googlers.

**Comment by DKhalil** [comment]
I submitted a PR #1102 to fix this but so far haven't gotten any response, @Akryum any possibility to merge this?
