### ISSUE TITLE
Fatal error when launching vue-devtools "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by BrayanIribe** [vuejs/vue-devtools#1088]
### Version
5.1.1

### Browser and OS info
Windows 10 x64
Node version: v10.16.3
NPM version: 6.9.0

### Steps to reproduce
Just follow the install instructions of standalone app and the error will happen.

```bash
> npm install -g @vue/devtools
> vue-devtools
```

### What is expected?
Launch the standalone app.

### What is actually happening?
The app is not launching. Instead, is showing a error dialog wth the following contents:

```
A JavaScript error occurred in the main process.

Uncaught Exception:
C:\Users\user\AppData\Roaming\npm\node_modules\@vue\devtools\node_mod...:347
   ...options
   ^^^
   SyntaxError: Unexpeted token...
     at createScript (vm.js:53:10)
     at Object.runInThisContext (vm.js:95:10)
     at Module._compile (module.js:543:28)
     at Object.Module._extensions.js (module.js:580:10)
     at Module.load (module.js:488:32)
     at tryModuleLoad (module.js:447:12)
     at Function.Module._load (module.js:439:3)
     at Module.require (module.js:498:17)
     at require (internal/module.js:20:19)
     at Object.<anonymus>
     (C:\Users\user\AppData\Roaming\npm\node_modules\@vue\devtools\node_mod...:19)
```

<p align="center">
<img src="https://user-images.githubusercontent.com/520683/67149224-7debda80-f25d-11e9-9647-d755d0ad0c22.png" alt="error">
</p>

**Comment by BrayanIribe** [comment]
I followed the next thread: [https://github.com/vuejs/vue-devtools/issues/1071](https://github.com/vuejs/vue-devtools/issues/1071).

That workaround fixed my problem, however I did some modifications:

```bash
#start server
> node %appdata%\npm\node_modules\@vue\devtools\server.js
#start desktop app
> %appdata%\npm\node_modules\@vue\devtools\node_modules\electron\dist\electron.exe

**Comment by huangbuchao** [comment]
electron version is too low, so that node not support ...spread operator.
upgrade package.json: electron: "^6.0.0" to solve.

**Comment by huangbuchao** [comment]
electron: "^2.0.0" is Compatible.

**Comment by huangbuchao** [comment]
> electron version is too low, so that node not support ...spread operator.
> upgrade package.json: electron: "^6.0.0" to solve.

recommend "^2.0.0"
