### ISSUE TITLE
下载后 npm run build报错  是需要安装webpack吗？

### ISSUE THREAD

**Issue by BOSSLMH** [vuejs/vue-devtools#1143]
> vue-devtools@5.3.3 build D:\myFile\vue-devtools-dev
> cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules

'webpack' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at notFoundError (D:\myFile\vue-devtools-dev\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\myFile\vue-devtools-dev\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\myFile\vue-devtools-dev\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (D:\myFile\vue-devtools-dev\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--progress', '--hide-modules' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-devtools@5.3.3 build: `cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-devtools@5.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2020-01-07T09_36_44_396Z-debug.log

**Comment by 1067831145** [comment]
请问这个问题解决了吗

**Comment by chengtaocode** [comment]
这个问题是CMD无法识别webpack命令，需要下载webpack，全局安装的webpack没用，使用yarn add -D -W webpack-cli下载webpack,然后在npm run build，这个需要的时间可能比较长，有可能需要5分钟耐心等待
