### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by 1067831145** [vuejs/vue-devtools#1166]
leguan@leguandeMacBook-Pro vue-devtools % npm run build

> vue-devtools@5.3.3 build /Users/leguan/Desktop/dectools/vue-devtools
> cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules

events.js:298
      throw er; // Unhandled 'error' event
      ^
Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--progress', '--hide-modules' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-devtools@5.3.3 build: `cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-devtools@5.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leguan/.npm/_logs/2020-02-11T10_00_31_261Z-debug.log

**Comment by GuoDapeng** [comment]
啥意思？被机器人关掉了？？？我想在edge上安装，找了很久安装包了……
