### ISSUE TITLE
Cannot find module '/home/quoniam/version-control/vue-devtools/install.js'

### ISSUE THREAD

**Issue by quoniammm** [vuejs/vue-devtools#145]
```
System:Ubuntu Xenial Xerus (development branch)
```

```
the result of node install.js:
```

```
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/quoniam/version-control/vue-devtools/install.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

How can I solve this problem?

**Comment by posva** [comment]
Sorry for the delay. There's no `install.js` file. Maybe you were looking for `npm install`
