### ISSUE TITLE
connect ETIMEDOUT 74.125.23.128:80

### ISSUE THREAD

**Issue by QuoniamYIF** [vuejs/vue-devtools#149]
when I run the command of npm install,the problem occurs.
what is the resaon for it?

```
$ npm install
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> chromedriver@2.24.1 install D:\vue-devtools\node_modules\chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.24/chromedriver_win32.zip
Saving to C:\Users\zhuangwy\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 74.125.23.128:80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node.exe" "D:\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vue-devtools\npm-debug.log
```

**Comment by simplesmiler** [comment]
Was not able to reproduce the timeout issue.
Make sure http://chromedriver.storage.googleapis.com/ is available from your network.

**Comment by karol-f** [comment]
What has worked for me:

```
npm install -g webdriver-manager
webdriver-manager update
```

and then `npm i` on project.
