### ISSUE TITLE
Show errors when excute `npm run build` command. Which module I do not install?

### ISSUE THREAD

**Issue by sarazhang123** [vuejs/vue-devtools#85]
```
vue-devtools@1.1.6 build /home/user/Cool/vue-devtools
> cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules

 10% 0/1 build modules/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:206
					throw e;
					      ^
Error: Cannot find module '../../modules/es6.object.keys'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/user/Cool/vue-devtools/node_modules/babel-runtime/node_modules/core-js/library/fn/object/keys.js:1:63)
...
```

**Comment by blake-newman** [comment]
Any more information on this? Closing for now. Please reopen if your still experience this issue.
